#!/bin/sh

echo "-- Start $1 --"

filename=$1

check_errs()
{
  # Function. Parameter 1 is the return code
  # Para. 2 is text to display on failure.
  if [ "${1}" -ne "0" ]; then

    #echo "ERROR # ${1} : ${2}"
    #exit ${1}

    echo "-- end $filename --"
    exit 9
  fi
}



index=1
while [ $index -lt 1000 ]
do
   #echo "Running #"$index
   #echo "" "$1"
    ./pbnsolve -b -u -c -n$index "$1"
    check_errs $? 
    index=`expr $index + 1`
done
